/**
 * Mock events. These are real payload responses from the Meetup API so you can (for now) base your templating around these properties.
 * Meetup API docs: https://www.meetup.com/meetup_api/docs/:urlname/events/#list
 */
export default [
  {
    created: 1588769590000,
    duration: 5400000,
    id: 'bxrbsryccgbfb',
    name: 'The basics of REST with Matt Trask',
    rsvp_limit: 70,
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1617478200000,
    local_date: '2021-04-03',
    local_time: '14:30',
    updated: 1617386841000,
    utc_offset: -18000000,
    waitlist_count: 0,
    yes_rsvp_count: 39,
    venue: {
      id: 26906060,
      name: 'Online event',
      repinned: true,
      country: '',
      localized_country_name: '',
    },
    is_online_event: true,
    group: {
      created: 1488987864000,
      name: 'freeCodeCamp Nashville',
      id: 22817838,
      join_mode: 'open',
      lat: 36.16999816894531,
      lon: -86.77999877929688,
      urlname: 'freeCodeCamp-Nashville',
      who: 'Campers',
      localized_location: 'Nashville, TN',
      state: 'TN',
      country: 'us',
      region: 'en_US',
      timezone: 'US/Central',
    },
    link: 'https://www.meetup.com/freeCodeCamp-Nashville/events/bxrbsryccgbfb/',
    description: `<p>REST is a ubiquitous term in web development these days. Understanding what REST is and what the headers, verbs, codes and more all mean is a daunting challenge and this talk will help break down what some of the more popular headers mean, how to use the status codes and how to use the HTTP verb.</p> <p>Matt Trask is a Senior Software Architect at Primitive in Nashville, TN and host of the podcast "APIs you won't hate!"</p> `,
    how_to_find_us:
      'https://app.toucan.events/go/159989b3-7a8a-478b-a162-68ef176e8fc1',
    visibility: 'public',
    member_pay_fee: false,
  },
  {
    created: 1611614453000,
    duration: 7200000,
    id: 'sgwqdsyccgbjb',
    name: 'Practice solving algorithms and data structure problems',
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1617750000000,
    local_date: '2021-04-06',
    local_time: '18:00',
    updated: 1611614453000,
    utc_offset: -18000000,
    waitlist_count: 0,
    yes_rsvp_count: 12,
    venue: {
      id: 26906060,
      name: 'Online event',
      repinned: false,
      country: '',
      localized_country_name: '',
    },
    is_online_event: true,
    group: {
      created: 1488987864000,
      name: 'freeCodeCamp Nashville',
      id: 22817838,
      join_mode: 'open',
      lat: 36.16999816894531,
      lon: -86.77999877929688,
      urlname: 'freeCodeCamp-Nashville',
      who: 'Campers',
      localized_location: 'Nashville, TN',
      state: 'TN',
      country: 'us',
      region: 'en_US',
      timezone: 'US/Central',
    },
    link: 'https://www.meetup.com/freeCodeCamp-Nashville/events/sgwqdsyccgbjb/',
    description:
      '<p>In this weekly event, we will practice algorithms and data-structure coding skills.</p> <p>Whether you are improving your problem-solving skills or practicing for an interview, join us as we group up and tackle coding problems.</p> <p>These problems will be found on websites like leetcode, codewars, and hackerrank.</p> <p>The coding will be done on a google word document or a third-party website. We’ll get into the details in the meetup.</p> <p>Structure:</p> <p>10 minutes: Intro and social<br/>5 - 10 minutes: Explain format<br/>60 - 90 minutes: Solving problems</p> <p>We stay on till 8pm, but you can leave prior to that.</p> <p>This is an online zoom event with details shared closer to the event.</p> <p>Photo by Alvaro Reyes on Unsplash</p> <p>Free Code Camp Nashville<br/>Code of Conduct<br/><a href="https://github.com/nashvillefcc/docs/blob/master/general/CODE_OF_CONDUCT.md" class="linkified">https://github.com/nashvillefcc/docs/blob/master/general/CODE_OF_CONDUCT.md</a></p> ',
    visibility: 'public',
    member_pay_fee: false,
  },
  {
    created: 1611614453000,
    duration: 7200000,
    id: 'sgwqdsyccgbrb',
    name: 'Practice solving algorithms and data structure problems',
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1618354800000,
    local_date: '2021-04-13',
    local_time: '18:00',
    updated: 1611614453000,
    utc_offset: -18000000,
    waitlist_count: 0,
    yes_rsvp_count: 5,
    venue: {
      id: 26906060,
      name: 'Online event',
      repinned: false,
      country: '',
      localized_country_name: '',
    },
    is_online_event: true,
    group: {
      created: 1488987864000,
      name: 'freeCodeCamp Nashville',
      id: 22817838,
      join_mode: 'open',
      lat: 36.16999816894531,
      lon: -86.77999877929688,
      urlname: 'freeCodeCamp-Nashville',
      who: 'Campers',
      localized_location: 'Nashville, TN',
      state: 'TN',
      country: 'us',
      region: 'en_US',
      timezone: 'US/Central',
    },
    link: 'https://www.meetup.com/freeCodeCamp-Nashville/events/sgwqdsyccgbrb/',
    description:
      '<p>In this weekly event, we will practice algorithms and data-structure coding skills.</p> <p>Whether you are improving your problem-solving skills or practicing for an interview, join us as we group up and tackle coding problems.</p> <p>These problems will be found on websites like leetcode, codewars, and hackerrank.</p> <p>The coding will be done on a google word document or a third-party website. We’ll get into the details in the meetup.</p> <p>Structure:</p> <p>10 minutes: Intro and social<br/>5 - 10 minutes: Explain format<br/>60 - 90 minutes: Solving problems</p> <p>We stay on till 8pm, but you can leave prior to that.</p> <p>This is an online zoom event with details shared closer to the event.</p> <p>Photo by Alvaro Reyes on Unsplash</p> <p>Free Code Camp Nashville<br/>Code of Conduct<br/><a href="https://github.com/nashvillefcc/docs/blob/master/general/CODE_OF_CONDUCT.md" class="linkified">https://github.com/nashvillefcc/docs/blob/master/general/CODE_OF_CONDUCT.md</a></p> ',
    visibility: 'public',
    member_pay_fee: false,
  },
];
